blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    Time : 2018/9/22 10:46
    File : urls.py
    __author__ = 'hdy'
"""
from django.urls import path, re_path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path('post/(?P<pk>[0-9]+)/', views.PostDetailView.as_view(), name='detail'),
    re_path('archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/', views.ArchivesView.as_view(), name='archives'),
    re_path('category/(?P<pk>[0-9]+)/', views.CategoryView.as_view(), name='category'),
    re_path('tag/(?P<pk>[0-9]+)/', views.TagView.as_view(), name='tag'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('search/', include('haystack.urls')),
    re_path('^all/rss/$', AllPostsRssFeed(), name='rss'),

]

templates/__base__.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<!-- saved from url=(0038)https://v3.bootcss.com/examples/blog/# -->
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/blog.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/highlights/github.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="blog-masthead navbar-default navbar-fixed-top">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url 'blog:index' %}">Home</a>
          <a class="blog-nav-item" href="#">New features</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="#">New hires</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <br>
        <br>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">


              {% block main %}
              {% endblock %}

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module sidebar-module-inset">
            <h4>Archives</h4>
              {% archives as date_list %}
            <ol class="list-unstyled">
              {% for date in date_list %}
                <li>
                    <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                </li>
              {% empty %}
                    暂无
              {% endfor %}
            </ol>
          </div>

          <div class="sidebar-module sidebar-module-inset">
          <h4>分类</h4>
          {% get_categories as category_list %}
                <ul class="list-unstyled">
                    {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span
                                    class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                    {% empty %}
                        暂无分类！
                    {% endfor %}
                </ul>
          </div>

          <div class="sidebar-module sidebar-module-inset">
              <h4>标签</h4>
              {% get_tags as tag_list %}
              <ol class="list-unstyled">
                  {% for tag in tag_list %}
                      <li>
                          <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                      </li>
                  {% empty %}
                      暂无标签！
                  {% endfor %}
              </ol>
          </div>

          <div class="sidebar-module sidebar-module-inset">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <a href="{% url 'rss' %}">RSS</a>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'blog/js/jquery-3.3.1.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'blog/css/bootstrap.min.css' %}"></script>

</body></html>